### ISSUE TITLE
Breaking Changes with actions/download-artifact v4

### ISSUE THREAD

**Issue by bflad** [hashicorp/ghaction-terraform-provider-release#76]
## Description

The latest v3 major releases of actions/upload-artifact and actions/download-artifact are incompatible with the new v4 major releases of each. The shared workflows in this repository will at some point (soon-ish?) need to be updated to v4, but the calling repositories could still be using v3 since they own the release note uploads. e.g. a now errant release workflow (where v3 used to work fine):

```yaml
jobs:
  go-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.go-version.outputs.version }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - id: go-version
        run: echo "name=version::$(cat ./.go-version)" >> "$GITHUB_OUTPUT"
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Generate Release Notes
        run: sed -n -e "1{/# /d;}" -e "2{/^$/d;}" -e "/# $(git describe --abbrev=0 --exclude="$(git describe --abbrev=0 --match='v*.*.*' --tags)" --match='v*.*.*' --tags | tr -d v)/q;p" CHANGELOG.md > release-notes.txt
      - uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: release-notes
          path: release-notes.txt
          retention-days: 1
  terraform-provider-release:
    name: 'Terraform Provider Release'
    needs: [go-version, release-notes]
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/hashicorp.yml@v2
    # ...
```

## Proposal

Cut new major version of this repository with actions/download-artifact v4 in the shared workflows. Notify stakeholders.
